# Generated by Django 4.2.11 on 2024-04-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choosemug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priceM', models.DecimalField(decimal_places=2, max_digits=4)),
                ('priceL', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dImage', models.URLField()),
            ],
        ),
    ]
