# Generated by Django 4.2.11 on 2024-04-25 08:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choosemug', '0002_dad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mom',
            name='mug_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
