# Generated by Django 4.2.11 on 2024-04-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choosemug', '0003_mom_mug_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mom',
            name='pImage',
        ),
    ]
