# Generated by Django 4.2.11 on 2024-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choosemug', '0004_remove_mom_pimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mom',
            name='priceL',
        ),
        migrations.RemoveField(
            model_name='mom',
            name='priceM',
        ),
        migrations.AddField(
            model_name='mom',
            name='colorA',
            field=models.CharField(default='White', max_length=120),
        ),
        migrations.AddField(
            model_name='mom',
            name='colorB',
            field=models.CharField(default='Black', max_length=120),
        ),
    ]
