# Generated by Django 4.2.11 on 2024-04-25 10:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choosemug', '0005_remove_mom_pricel_remove_mom_pricem_mom_colora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mom',
            old_name='colorA',
            new_name='colorAm',
        ),
        migrations.RenameField(
            model_name='mom',
            old_name='colorB',
            new_name='colorBm',
        ),
        migrations.RemoveField(
            model_name='dad',
            name='dImage',
        ),
        migrations.RemoveField(
            model_name='dad',
            name='priceL',
        ),
        migrations.RemoveField(
            model_name='dad',
            name='priceM',
        ),
        migrations.AddField(
            model_name='dad',
            name='colorAd',
            field=models.CharField(default='White', max_length=120),
        ),
        migrations.AddField(
            model_name='dad',
            name='colorBd',
            field=models.CharField(default='Black', max_length=120),
        ),
        migrations.AddField(
            model_name='dad',
            name='mug_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
