# Generated by Django 4.2.11 on 2024-05-15 11:04

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0006_alter_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_alt',
            field=models.CharField(default='No alt text provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='coffee_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='placeholder', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='review/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='review',
            name='excerpt',
            field=models.TextField(default='No alt text provided', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='Coffee Shop Name', max_length=200),
        ),
    ]
