# Generated by Django 4.2.11 on 2024-05-16 07:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coffeeshop", "0007_review_image_alt_alter_review_coffee_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="coffee_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
