# Generated by Django 4.2.11 on 2024-05-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_rename_featured_image_about_profile_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CollaborateRequest",
            new_name="ContactUs",
        ),
    ]
