# Generated by Django 4.2.11 on 2024-05-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0005_rename_collaboraterequest_contactus"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactUs",
            new_name="Contact",
        ),
    ]
